[versions]
agp = "8.11.1"
androidCompileSdk = "36"
androidMinSdk = "24"
androidTargetSdk = "36"
androidxActivity = "1.10.1"
androidxAppcompat = "1.7.1"
androidxCore = "1.17.0"
androidxEspresso = "3.7.0"
androidxLifecycle = "2.9.3"
androidxTestExt = "1.3.0"
composeMultiplatform = "1.9.0"
junit = "4.13.2"
kotlin = "2.2.10"
ktor = "3.3.0"
kotlinSerialization = "1.9.0"
koin = "4.1.1"
koinComposeMultiplatform = "4.1.1"
viewmodelCompose = "2.8.0"
roomMultiplatform = "2.8.1"
ksp = "2.2.0-2.0.2"
coil = "3.3.0"
sqlite = "2.6.1"
datetime = "0.7.1"
dataStore = "1.1.7"
timber = "5.0.1"

[libraries]
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinTestJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidxCoreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidxTestExtJunit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidxEspressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspresso" }
androidxAppcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }


#DI
koinCore = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koinAndroid = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koinCompose = { module = "io.insert-koin:koin-compose", version.ref = "koinComposeMultiplatform" }

#DB
roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomMultiplatform" }
roomRuntime = { group = "androidx.room", name = "room-runtime", version.ref = "roomMultiplatform" }
sqliteBundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

#COIL
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coilCompose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coilComposeCore = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil" }
coilKtor = { module = "io.coil-kt.coil3:coil-network-ktor", version.ref = "coil" }

# Ktor
ktorCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorSerialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorAuth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktorLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktorAndroid = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktorIos = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktorCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorTest = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }


#DATASTORE
dataStore = { module = "androidx.datastore:datastore", version.ref = "dataStore" }
dataStorePreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }


[bundles]
androidx = [
    "androidxActivityCompose",
    "androidxAppcompat",
    "androidxCoreKtx"
]

koinAndroid = [
    "koinCore",
    "koinAndroid",
    "koinCompose",
]

dataStore = [
    "dataStore",
    "dataStorePreferences"
]

coil = [
    "coil",
    "coilCompose",
    "coilComposeCore",
]

ktorMultiplatform = [
    "ktorCore",
    "ktorNegotiation",
    "ktorSerialization",
    "ktorAuth",
    "ktorLogging",
    "ktorTest",
    "ktorCio",
]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
roomGradlePlugin = { id = "androidx.room", version.ref = "roomMultiplatform" }