build-job:
  stage: build
  image: gradle:8.11.1-jdk17
  variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  cache:
    key: gradle-cache
    paths:
      - .gradle/
  script:
    - chmod +x ./gradlew
    - ./gradlew build --stacktrace
  artifacts:
    paths:
      - app/build/outputs/
      - build/outputs/